export interface User {
    id: number; // assuming the id is automatically generated by MongoDB, you might omit this field when inserting new users
    first_name: string;
    last_name: string;
    email: string;
  }
  